name: ecommerzadmin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  splash_view: ^2.0.1


  #  state management and storage
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  uuid: ^4.1.0


  # firebase
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  #flutter_launcher_icons: "^0.13.1"
  ## flutter pub run flutter_launcher_icons:main  ~ for set launcher icon
  #  change_app_package_name: ^1.1.0
  ## last package name was com.example.ecommerzadmin and new is univers.soft.ecz.admin    [ctrl + shift + r] for replacing all old package name
  ## Notice for old package dependencies like firebase .... reconnect or re create
  ## [Dont change package name after publishing the app in store]

#  flutter_app_name: ^0.1.1
#flutter_app_name:
#    name: "Ecz Admin"
#    #flutter pub run flutter_app_name   ~ for changing app name

flutter:

  uses-material-design: true

  assets:
    - assets/